version: "3.8"

services:
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payout_system
    volumes:
      - dbdata:/var/lib/mysql

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API endpoint for Laravel
      - "9001:9001"   # Web console
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - minio
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: payout_system
      DB_USERNAME: root
      DB_PASSWORD: root

      # 👇 add these so Laravel can talk to MinIO
      FILESYSTEM_DISK: s3
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: laravel-payments
      AWS_ENDPOINT: http://minio:9000
      AWS_USE_PATH_STYLE_ENDPOINT: "true"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  dbdata:
  minio_data:
